### ISSUE TITLE
usability improvement suggestions

### ISSUE THREAD

**Issue by umputun** [paskal/telegram-banhammer#1]
- add `ban_to_time` allowing a human-friendly formal, like `dd:mm:hhThh:mm:ss`. TG seems to show all the times in the local tz, so this time can be local
- build binaries for all the popular platforms as the docker images doesn't make it easy to use, much simpler to run a binary. publish binaries. Probably this can be done with [go-releaser](https://goreleaser.com) plus [upload-artifact ](https://github.com/actions/upload-artifact)
- allow all the credentials parameter to be loaded from some file, i.e. like aws cli allows. will simplify the usage
- document how credential cached and how to clear it
- nit: underscore-style param are odd and unusual. Probably making them with `-` instead of `_` will make it more traditional
- add Makefile with 3 targets: update (download latest binary for user's platform), list and apply, or smth like this
- `--not-dry-run` is a strange animal for sure. I don't know if this one even needed anymore since collection of ids and the actual ban are two distinct steps, but if needed I'd rather suggest to flip it, i.e. `--dry`

**Comment by paskal** [comment]
Only makefile and loading credentials from the file are not implemented, but I think I'll leave it like that as for such a once-in-a-lifetime used tool, it's okay to have everything in the CLI. I am resolving the issue. The state of the program after changes would be named v1.0.0
